/**
 * Imports
 */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// Redux
import { ReduxProvider } from '@/redux/provider'

// Components
import HeaderDefault from '@/components/HeaderDefault'

// Vercel
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-xl mx-auto my-0 bg-primary`}>
        <ReduxProvider>
          <HeaderDefault />
          {children}
          <Analytics />
        </ReduxProvider>
      </body>
    </html>
  )
}
